left_arm:
  # TRAC IK
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: 'Distance'
  position_only_ik: true
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  # KDL
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_attempts: 3
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.005
  # IK Fast
  # kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
  # kinematics_solver_attempts: 1
  # kinematics_solver_search_resolution: 0.01
  # kinematics_solver_timeout: 0.0001
left_arm_90:
  # TRAC IK
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: 'Distance'
  position_only_ik: true
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  # KDL
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_attempts: 3
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.005
left_arm_cartesian:
    # TRAC IK
    # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    # solve_type: 'Distance'
    # position_only_ik: false
    # kinematics_solver_search_resolution: 0.005
    # kinematics_solver_timeout: 0.005
    # KDL
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_attempts: 3
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.005
    # IK Fast
    # kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
    # kinematics_solver_attempts: 1
    # kinematics_solver_search_resolution: 0.01
    # kinematics_solver_timeout: 0.0001
left_arm_90_cartesian:
    # TRAC IK
    # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    # solve_type: 'Distance'
    # position_only_ik: false
    # kinematics_solver_search_resolution: 0.005
    # kinematics_solver_timeout: 0.005
    # KDL
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_attempts: 3
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.005
left_arm_realsense_cartesian:
    # TRAC IK
    # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    # solve_type: 'Distance'
    # position_only_ik: false
    # kinematics_solver_search_resolution: 0.005
    # kinematics_solver_timeout: 0.005
    # KDL
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_attempts: 3
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.005
left_arm_realsense:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
# uncomment to use ikfast kinematics plugin
# kinematics_solver: baxter_right_arm_kinematics/IKFastKinematicsPlugin
# kinematics_solver_attempts: 5
  SolveType: 'Distance'
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
right_arm:
  # TRAC IK
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: 'Distance'
  position_only_ik: true
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  # KDL
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_attempts: 3
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.005
  # IK Fast
  # kinematics_solver: baxter_right_arm_kinematics/IKFastKinematicsPlugin
  # kinematics_solver_attempts: 1
  # kinematics_solver_search_resolution: 0.01
  # kinematics_solver_timeout: 0.0001
right_arm_90:
  # TRAC IK
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  solve_type: 'Distance'
  position_only_ik: true
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  # KDL
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  # kinematics_solver_attempts: 3
  # kinematics_solver_search_resolution: 0.005
  # kinematics_solver_timeout: 0.005
right_arm_cartesian:
    # TRAC IK
    # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    # solve_type: 'Distance'
    # position_only_ik: false
    # kinematics_solver_search_resolution: 0.005
    # kinematics_solver_timeout: 0.005
    # KDL
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_attempts: 3
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.005
    # IK Fast
    # kinematics_solver: baxter_right_arm_kinematics/IKFastKinematicsPlugin
    # kinematics_solver_attempts: 1
    # kinematics_solver_search_resolution: 0.01
    # kinematics_solver_timeout: 0.0001
right_arm_90_cartesian:
    # TRAC IK
    # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    # solve_type: 'Distance'
    # position_only_ik: false
    # kinematics_solver_search_resolution: 0.005
    # kinematics_solver_timeout: 0.005
    # KDL
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_attempts: 3
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.005
right_arm_realsense_cartesian:
    # TRAC IK
    # kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
    # solve_type: 'Distance'
    # position_only_ik: false
    # kinematics_solver_search_resolution: 0.005
    # kinematics_solver_timeout: 0.005
    # KDL
    kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
    kinematics_solver_attempts: 3
    kinematics_solver_search_resolution: 0.005
    kinematics_solver_timeout: 0.005
right_arm_realsense:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
# uncomment to use ikfast kinematics plugin
# kinematics_solver: baxter_right_arm_kinematics/IKFastKinematicsPlugin
# kinematics_solver_attempts: 5
  SolveType: 'Distance'
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
# left_hand:
#   #  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   # SolveType: 'Distance'
#   # uncomment to use ikfast kinematics plugin
#   # kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
#   kinematics_solver_attempts: 5
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#
# left_hand_90:
#   #  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   # SolveType: 'Distance'
#   # uncomment to use ikfast kinematics plugin
#   # kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
#   kinematics_solver_attempts: 5
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#
# right_hand:
#  #  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   # SolveType: 'Distance'
#  # uncomment to use ikfast kinematics plugin
#  # kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
#   kinematics_solver_attempts: 5
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
#
# left_hand_realsense:
# #  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   # SolveType: 'Distance'
# # uncomment to use ikfast kinematics plugin
# # kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
#   kinematics_solver_attempts: 5
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005

# both_arms:
# #  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#   kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
#   SolveType: 'Distance'
# # uncomment to use ikfast kinematics plugin
# # kinematics_solver: baxter_left_arm_kinematics/IKFastKinematicsPlugin
#   kinematics_solver_attempts: 5
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005
