sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /registered_empty_shelf
   max_range: 1.5
   padding_offset: 0.1
   padding_scale: 1.0
   # padding_scale: 1.0
   # frame_subsample: 1
   # point_subsample: 1
   # filtered_cloud_topic: /filtered_cloud
